import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='p-0 m-0 box-border overflow-y-auto'>
      <body className={inter.className + 'p-0 m-0 box-border'}>{children}</body>
    </html>
  )
}
